namespace Nedev.FileConverters.PptxToPdf;

public static class ShapeTypeMapping
{
    public static ShapeType FromPresetGeometry(string? prst)
    {
        if (string.IsNullOrEmpty(prst))
            return ShapeType.Rectangle;

        return prst switch
        {
            // ??????
            "rect" => ShapeType.Rectangle,
            "roundRect" => ShapeType.RoundRectangle,
            "ellipse" => ShapeType.Ellipse,
            "triangle" => ShapeType.Triangle,
            "rtTriangle" => ShapeType.Triangle,
            "parallelogram" => ShapeType.Parallelogram,
            "trapezoid" => ShapeType.Trapezoid,
            "diamond" => ShapeType.Diamond,
            "pentagon" => ShapeType.Pentagon,
            "hexagon" => ShapeType.Hexagon,
            "heptagon" => ShapeType.Heptagon,
            "octagon" => ShapeType.Octagon,
            "decagon" => ShapeType.Decagon,
            "dodecagon" => ShapeType.Dodecagon,
            "pie" => ShapeType.Pie,
            "chord" => ShapeType.Chord,
            "teardrop" => ShapeType.Teardrop,
            "frame" => ShapeType.Frame,
            "halfFrame" => ShapeType.HalfFrame,
            "corner" => ShapeType.LShape,
            "diagStripe" => ShapeType.DiagonalStripe,
            "cross" => ShapeType.Cross,
            "plus" => ShapeType.Plus,
            "plaque" => ShapeType.Plaque,
            "can" => ShapeType.Can,
            "cube" => ShapeType.Cube,
            "bevel" => ShapeType.Bevel,
            "donut" => ShapeType.Donut,
            "noSmoking" => ShapeType.NoSmoking,
            "blockArc" => ShapeType.BlockArc,
            "foldedCorner" => ShapeType.FoldedCorner,
            "smileyFace" => ShapeType.SmileyFace,
            "heart" => ShapeType.Heart,
            "lightningBolt" => ShapeType.LightningBolt,
            "sun" => ShapeType.Sun,
            "moon" => ShapeType.Moon,
            "cloud" => ShapeType.Cloud,
            "arc" => ShapeType.Arc,
            "bracketPair" => ShapeType.BracketPair,
            "bracePair" => ShapeType.BracePair,
            "leftBracket" => ShapeType.LeftBracket,
            "rightBracket" => ShapeType.RightBracket,
            "leftBrace" => ShapeType.LeftBrace,
            "rightBrace" => ShapeType.RightBrace,

            // ???
            "rightArrow" => ShapeType.RightArrow,
            "leftArrow" => ShapeType.LeftArrow,
            "upArrow" => ShapeType.UpArrow,
            "downArrow" => ShapeType.DownArrow,
            "leftRightArrow" => ShapeType.LeftRightArrow,
            "upDownArrow" => ShapeType.UpDownArrow,
            "quadArrow" => ShapeType.QuadArrow,
            "leftRightUpArrow" => ShapeType.LeftRightUpArrow,
            "bentArrow" => ShapeType.BentArrow,
            "uturnArrow" => ShapeType.UTurnArrow,
            "leftUpArrow" => ShapeType.LeftUpArrow,
            "bentUpArrow" => ShapeType.BentUpArrow,
            "curvedRightArrow" => ShapeType.CurvedRightArrow,
            "curvedLeftArrow" => ShapeType.CurvedLeftArrow,
            "curvedUpArrow" => ShapeType.CurvedUpArrow,
            "curvedDownArrow" => ShapeType.CurvedDownArrow,
            "stripedRightArrow" => ShapeType.StripedRightArrow,
            "notchedRightArrow" => ShapeType.NotchedRightArrow,
            "pentagonArrow" => ShapeType.PentagonArrow,
            "chevron" => ShapeType.Chevron,
            "rightArrowCallout" => ShapeType.RightArrowCallout,
            "leftArrowCallout" => ShapeType.LeftArrowCallout,
            "upArrowCallout" => ShapeType.UpArrowCallout,
            "downArrowCallout" => ShapeType.DownArrowCallout,
            "leftRightArrowCallout" => ShapeType.LeftRightArrowCallout,
            "upDownArrowCallout" => ShapeType.UpDownArrowCallout,
            "quadArrowCallout" => ShapeType.QuadArrowCallout,
            "circularArrow" => ShapeType.CircularArrow,

            // ?????            "flowChartProcess" => ShapeType.FlowChartProcess,
            "flowChartDecision" => ShapeType.FlowChartDecision,
            "flowChartInputOutput" => ShapeType.FlowChartInputOutput,
            "flowChartPredefinedProcess" => ShapeType.FlowChartPredefinedProcess,
            "flowChartInternalStorage" => ShapeType.FlowChartInternalStorage,
            "flowChartDocument" => ShapeType.FlowChartDocument,
            "flowChartMultidocument" => ShapeType.FlowChartMultidocument,
            "flowChartTerminator" => ShapeType.FlowChartTerminator,
            "flowChartPreparation" => ShapeType.FlowChartPreparation,
            "flowChartManualInput" => ShapeType.FlowChartManualInput,
            "flowChartManualOperation" => ShapeType.FlowChartManualOperation,
            "flowChartConnector" => ShapeType.FlowChartConnector,
            "flowChartPunchedCard" => ShapeType.FlowChartPunchedCard,
            "flowChartPunchedTape" => ShapeType.FlowChartPunchedTape,
            "flowChartSummingJunction" => ShapeType.FlowChartSummingJunction,
            "flowChartOr" => ShapeType.FlowChartOr,
            "flowChartCollate" => ShapeType.FlowChartCollate,
            "flowChartSort" => ShapeType.FlowChartSort,
            "flowChartExtract" => ShapeType.FlowChartExtract,
            "flowChartMerge" => ShapeType.FlowChartMerge,
            "flowChartOfflineStorage" => ShapeType.FlowChartOfflineStorage,
            "flowChartOnlineStorage" => ShapeType.FlowChartOnlineStorage,
            "flowChartMagneticTape" => ShapeType.FlowChartMagneticTape,
            "flowChartMagneticDisk" => ShapeType.FlowChartMagneticDisk,
            "flowChartMagneticDrum" => ShapeType.FlowChartMagneticDrum,
            "flowChartDisplay" => ShapeType.FlowChartDisplay,
            "flowChartDelay" => ShapeType.FlowChartDelay,
            "flowChartAlternateProcess" => ShapeType.FlowChartAlternateProcess,
            "flowChartOffpageConnector" => ShapeType.FlowChartOffpageConnector,

            // ???
            "rectangularCallout" => ShapeType.RectangularCallout,
            "roundedRectangularCallout" => ShapeType.RoundedRectangularCallout,
            "ovalCallout" => ShapeType.OvalCallout,
            "cloudCallout" => ShapeType.CloudCallout,
            "lineCallout1" => ShapeType.LineCallout1,
            "lineCallout2" => ShapeType.LineCallout2,
            "lineCallout3" => ShapeType.LineCallout3,
            "lineCallout1AccentBar" => ShapeType.LineCallout1AccentBar,
            "lineCallout2AccentBar" => ShapeType.LineCallout2AccentBar,
            "lineCallout3AccentBar" => ShapeType.LineCallout3AccentBar,
            "lineCallout1NoBorder" => ShapeType.LineCallout1NoBorder,
            "lineCallout2NoBorder" => ShapeType.LineCallout2NoBorder,
            "lineCallout3NoBorder" => ShapeType.LineCallout3NoBorder,
            "lineCallout1BorderAndAccentBar" => ShapeType.LineCallout1BorderAndAccentBar,
            "lineCallout2BorderAndAccentBar" => ShapeType.LineCallout2BorderAndAccentBar,
            "lineCallout3BorderAndAccentBar" => ShapeType.LineCallout3BorderAndAccentBar,

            // ????????            "star4" => ShapeType.Star4,
            "star5" => ShapeType.Star5,
            "star6" => ShapeType.Star6,
            "star7" => ShapeType.Star7,
            "star8" => ShapeType.Star8,
            "star10" => ShapeType.Star10,
            "star12" => ShapeType.Star12,
            "star16" => ShapeType.Star16,
            "star24" => ShapeType.Star24,
            "star32" => ShapeType.Star32,
            "ribbon" => ShapeType.Ribbon,
            "ribbon2" => ShapeType.Ribbon2,
            "ellipseRibbon" => ShapeType.EllipseRibbon,
            "ellipseRibbon2" => ShapeType.EllipseRibbon2,
            "verticalScroll" => ShapeType.VerticalScroll,
            "horizontalScroll" => ShapeType.HorizontalScroll,
            "wave" => ShapeType.Wave,
            "doubleWave" => ShapeType.DoubleWave,

            // ??????
            "actionButtonBlank" => ShapeType.ActionButtonBlank,
            "actionButtonHome" => ShapeType.ActionButtonHome,
            "actionButtonHelp" => ShapeType.ActionButtonHelp,
            "actionButtonInformation" => ShapeType.ActionButtonInformation,
            "actionButtonForwardNext" => ShapeType.ActionButtonForwardNext,
            "actionButtonBackPrevious" => ShapeType.ActionButtonBackPrevious,
            "actionButtonEnd" => ShapeType.ActionButtonEnd,
            "actionButtonBeginning" => ShapeType.ActionButtonBeginning,
            "actionButtonReturn" => ShapeType.ActionButtonReturn,
            "actionButtonDocument" => ShapeType.ActionButtonDocument,
            "actionButtonSound" => ShapeType.ActionButtonSound,
            "actionButtonMovie" => ShapeType.ActionButtonMovie,

            // ?????            "straightConnector1" => ShapeType.StraightConnector,
            "elbowConnector" => ShapeType.ElbowConnector,
            "curvedConnector" => ShapeType.CurvedConnector,

            _ => ShapeType.AutoShape
        };
    }
}
